// no te olvides borrar este archivo luis
export const dataHarcodeada = {
	id: 6,
	id_documento: 14,
	id_periodo: 30,
	id_usuario: 2,
	id_empresa: null,
	id_departamento: 25,
	id_anexo: 65,
	id_sucursal: 8,
	id_almacen: 11,
	id_moneda: null,
	serie: '0001',
	numero: '00000001',
	fecha: '2024-03-11',
	tipo_cambio: 3.696,
	sub_total: 0,
	id_aprobador: 6,
	fecha_aprobacion: '2024-03-13',
	prioridad: 'baja',
	estado_aprobacion: 'anulado',
	estado_atencion: 'pendiente',
	observacion: '',
	c65_usuario: {
		id: 2,
		dni: '20440405143',
		username: 'JULIO JHOMPIERRE ROBLES AQUINO',
		username_short: 'J. ROBLES',
		email: 'jrobles@newid.club',
	},
	c65_periodo: {
		id: 30,
		anio: '2024',
		mes: '03',
		periodo: '202403',
		fecha_inicio: '2024-03-01',
		fecha_fin: '2024-03-31',
		estado_documento: 'abierto',
	},
	c65_departamento: {
		id: 25,
		codigo: '003',
		descripcion: 'SUB-GERENCIA DE TI',
	},
	c65_anexo: {
		id: 65,
		id_credencial: 25,
		codigo: '003',
		descripcion: 'SUB-GERENTE DE TI',
	},
	c65_sucursal: {
		id: 8,
		codigo: '001',
		descripcion: 'TRUJILLO',
		codigo_externo: '001',
	},
	c65_almacen: {
		id: 11,
		id_credencial: 8,
		codigo: '001',
		descripcion: 'ALMACÉN TRUJILLO',
		codigo_externo: '001',
		direccion: 'LOTE VD78 SECTOR VALDIVIA ALTA - HUANCHACO - TRUJILLO',
	},
	c65_empresa: null,
	c65_moneda: null,
	c65_aprobador: {
		id: 6,
		c31_usuario: {
			username: 'JULIO JHOMPIERRE ROBLES AQUINO',
			username_short: 'J. ROBLES',
		},
		fecha_aprobacion: '2024-04-18 20:28:26',
	},
	c65_detalle_anexo: [],
	contribuyente: {
		ruc: '20440405143',
		razon_social: 'SERVICIOS DE TRANSPORTE MINA SAC',
		direccion: 'LOTE VD SECTOR VALDIVIA ALTA - HUANCHACO',
	},
	detalle: [
		{
			id: 6,
			id_credencial: 6,
			id_documento_anexo: null,
			id_credencial_anexo: null,
			id_credencial_anexo_item: null,
			id_producto: 107,
			id_unidad_medida: 25,
			id_centro_costo: 179,
			position: 1,
			descripcion: 'PETROLEO DIESEL',
			cantidad_original: null,
			cantidad_solicitado: 20,
			cantidad_atendido: 20,
			precio_sin_igv: 0,
			sub_total: 0,
			id_empleado: 117,
			observacion: '',
			motivo: 'stk',
			c65_producto: {
				id: 107,
				id_unidad_medida: 25,
				id_segmento: 11,
				id_familia: 35,
				id_clase: 36,
				id_marca: null,
				id_modelo: null,
				codigo: '5MgGOTUgpp',
				codigo_sunat: '',
				codigo_externo: '',
				codigo_repuesto: '',
				descripcion: 'PETROLEO DIESEL',
				path: '',
				image_url: '',
				stock_minimo: '0.0000',
				sincronizado: true,
				c25_modelo: {
					descripcion: '',
				},
				c25_marca: {
					descripcion: '',
				},
			},
			c65_unidad_medida: {
				id: 25,
				codigo: 'GLN',
				codigo_externo: 'GLN',
				descripcion: 'GALONES',
			},
			c65_centro_costo: {
				id: 179,
				codigo: 'VENTAS',
				descripcion: 'VENTAS',
				id_empresa: 21,
				tipo: 'propio',
			},
			c65_empleado: {
				id: 117,
				dni: '70341089',
				nombre: 'JULIO JHOMPIERRE',
				apellido: 'ROBLES AQUINO',
				nombre_apellido: 'JULIO JHOMPIERRE ROBLES AQUINO',
				fecha_nacimiento: '1995-06-19',
				sexo: 'MASCULINO',
				licencia_conducir: '',
				short_name: 'J. ROBLES',
			},
		},
	],
}
