// no te olvides borrar este archivo luis
export const dataHarcodeada = {
	detalle: [
		{
			articuloId: 1,
			articulo: 'Articulo 1',
			marca: 'Marca 1',
			modelo: 'Modelo 1',
			serie: 'Serie 1',
			fechaIngreso: '2022-01-01',
			motivoIngreso: 'Ingreso 1',
			diagnostico: 'Diagnostico 1',
			observaciones: 'Observaciones 1',
		},
		{
			articuloId: 2,
			articulo: 'Articulo 2',
			marca: 'Marca 2',
			modelo: 'Modelo 2',
			serie: 'Serie 2',
			fechaIngreso: '2022-01-02',
			motivoIngreso: 'Ingreso 2',
			diagnostico: 'Diagnostico 2',
			observaciones: 'Observaciones 2',
		},
		{
			articuloId: 3,
			articulo: 'Articulo 3',
			marca: 'Marca 3',
			modelo: 'Modelo 3',
			serie: 'Serie 3',
			fechaIngreso: '2022-01-03',
			motivoIngreso: 'Ingreso 3',
			diagnostico: 'Diagnostico 3',
			observaciones: 'Observaciones 3',
		},
		{
			articuloId: 4,
			articulo: 'Articulo 4',
			marca: 'Marca 4',
			modelo: 'Modelo 4',
			serie: 'Serie 4',
			fechaIngreso: '2022-01-04',
			motivoIngreso: 'Ingreso 4',
			diagnostico: 'Diagnostico 4',
			observaciones: 'Observaciones 4',
		},
	],
}
