import type { Metadata } from "next";
import { textFont } from "@/config/fonts";
import { Providers } from "@/components";
import "./globals.css";

export const metadata: Metadata = {
  title: "TallerXpert",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={textFont.className}>{children}</body>
      </html>
    </Providers>
  );
}
