import type { Metadata } from "next";
import { textFont } from "@/config/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "TallerXpert",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={textFont.className}>{children}</body>
    </html>
  );
}
