### GET
GET http://localhost:8080/api/user

### POST
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "email": "usuario1",
  "password": "password usuario1",
  "clientId": "08c0b65e-afdb-4bc6-b6a1-b1808e404cd0"
}

############# CLIENT

### GET ALL
GET http://localhost:8080/api/client/

### GET BY ID
GET http://localhost:8080/api/client/08c0b65e-afdb-4bc6-b6a1-b1808e404cd0

### POST
POST http://localhost:8080/api/client
Content-Type: application/json

{
  "fullName": "nuevo cliente1",
  "address": "direccion nueva",
  "dni": 12265678,
  "city": "ciudad nueva",
  "phone": 12345678,
  "email": "email2nuevo@gmail.com"
}

### UPDATE BY ID
PATCH http://localhost:8080/api/client/08c0b65e-afdb-4bc6-b6a1-b1808e404cd0
Content-Type: application/json

{
  "name": "update cliente1",
  "address": "direccion nueva",
}

### DELETE BY ID
DELETE http://localhost:8080/api/client/08c0b65e-afdb-4bc6-b6a1-b1808e404cd0


########### SUPPLIER

### GET ALL
GET http://localhost:8080/api/supplier/

### POST
POST http://localhost:8080/api/supplier
Content-Type: application/json

{
  "name": "Honda",
  "cuit": 10786,
  "address": "Asturias 916",
  "city": "Buenos Aires",
  "phone": "+51789876557",
  "email": "hondaselect@gmail.com",
  "seller_name": "Luana Especi",
  "categories": {"hola":"hola"}
}