export { default as user } from './user.route'
export { default as workshop } from './workshop.route'
export { default as client } from './client.route'
export { default as signin } from './signin.route'
export { default as register } from './register.route'
export { default as profile } from './profile.route'
export { default as reparation } from './reparation.route'
export { default as product} from './product.route'
export { default as supplier} from './supplier.route'
